services:
  backend:
    container_name: udlatester_backend
    build:
      context: ./cases_backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql+psycopg2://udlatester:udlatester@udlatester_db:5432/udlatester
    restart: always
    networks:
      - udlatester_network

  frontend:
    container_name: udlatester_frontend
    build:
      context: ./cases_frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - udlatester_network
  
  db:
    container_name: udlatester_db
    image: postgres:latest
    environment:
      POSTGRES_USER: udlatester
      POSTGRES_PASSWORD: udlatester
      POSTGRES_DB: udlatester
    restart: always
    networks:
      - udlatester_network
    volumes:
      - udlatester_db_data:/var/lib/postgresql/data

networks:
  udlatester_network:
        external: true
    
volumes:
  udlatester_db_data:
