services:
  backend:
    container_name: udlatester_backend
    build:
      context: ./cases_backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql+psycopg2://udlatester:udlatester@udlatester_db:5432/udlatester
    restart: always
    networks:
      - udlatester_network

  frontend:
    container_name: udlatester_frontend
    build:
      context: ./cases_frontend
      dockerfile: Dockerfile
      args:
        - VITE_TITLE=UDLA Testing
        - VITE_CLIENT_ID=38793d3a-08f2-48bb-b579-ba4220f9433d
        - VITE_AUTHORITY=https://login.microsoftonline.com/2af6ae87-3287-4e29-a50a-680f5d852aa3
        - VITE_POPUP_REDIRECT_URI=/redirect
        - VITE_CASES_BACKEND_URL=https://udlatester-api.lerolero.com.ec
    environment:
      - NODE_ENV=production

    restart: always
    networks:
      - udlatester_network

  db:
    container_name: udlatester_db
    image: postgres:latest
    environment:
      POSTGRES_USER: udlatester
      POSTGRES_PASSWORD: udlatester
      POSTGRES_DB: udlatester
    restart: always
    networks:
      - udlatester_network
    volumes:
      - udlatester_db_data:/var/lib/postgresql/data

networks:
  udlatester_network:
    external: true

volumes:
  udlatester_db_data:
